import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { Theme, ThemePanel } from '@radix-ui/themes'
import "@radix-ui/themes/styles.css";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter", 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme accentColor="iris" scaling="110%">
          <NavBar />
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  )
}
